---
layout: archive
title: Zulip Chat Archive
permalink: /stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/stream/113488-general/index.html">general</a></h2>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html">error: unknown declaration _private</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com/">

<head><link href="/style.css" rel="stylesheet"></head>

{% raw %}

<a name="258154249"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258154249" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Floris van Doorn <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258154249">(Oct 19 2021 at 07:40)</a>:</h4>
<p>I got an error in the CI that I've never seen before, during the <code>export as low-level text file</code> step:</p>
<div class="codehilite" data-code-language="Text only"><pre><span></span><code>Run lean --recursive --export=mathlib.txt src/
  lean --recursive --export=mathlib.txt src/
  shell: /usr/bin/bash -e {0}
&lt;unknown&gt;:1:1: error: unknown declaration '_private.1263093571.lt'
Error: Process completed with exit code 1.
</code></pre></div>
<p><a href="https://github.com/leanprover-community/mathlib/runs/3932628186">https://github.com/leanprover-community/mathlib/runs/3932628186</a></p>
<p>Anyone knows what's up here? I already tried re-running all jobs, it's a reproducible error.</p>



<a name="258154348"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258154348" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Floris van Doorn <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258154348">(Oct 19 2021 at 07:41)</a>:</h4>
<p>Oh, this has been mentioned here<br>
<a href="#narrow/stream/113488-general/topic/bors.20failing">https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/bors.20failing</a><br>
Was there any solution to this? Is this just an unlucky hash collision or something?</p>



<a name="258154418"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258154418" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Floris van Doorn <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258154418">(Oct 19 2021 at 07:42)</a>:</h4>
<p><span class="user-mention" data-user-id="123965">@Bryan Gin-ge Chen</span></p>



<a name="258154816"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258154816" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Bryan Gin-ge Chen <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258154816">(Oct 19 2021 at 07:46)</a>:</h4>
<p>The error didn't come back after bors split the batch in the failure I linked to, so it being some kind of hash collision makes sense to me.</p>



<a name="258154852"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258154852" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Floris van Doorn <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258154852">(Oct 19 2021 at 07:47)</a>:</h4>
<p>Ok, thanks! I tried merging into master. Hopefully that "fixes" it.</p>



<a name="258155235"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258155235" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Kevin Buzzard <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258155235">(Oct 19 2021 at 07:50)</a>:</h4>
<p>I don't know anything about CI but I'm interested in learning what a hash collision is. I thought that a hash was something like a 64 character string of garbage and the chances of two different collections of files having the same hash was something we'd never see before the sun burnt out</p>



<a name="258156705"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258156705" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Ruben Van de Velde <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258156705">(Oct 19 2021 at 08:06)</a>:</h4>
<p>It depends on how many characters you use</p>



<a name="258157086"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258157086" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Floris van Doorn <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258157086">(Oct 19 2021 at 08:09)</a>:</h4>
<p>This is probably not an actual hash collision (because in that case I would expect an error of the form <code>declaration ... already exists</code>).<br>
As Ruben says, it depends on the number of characters you use. In the name of the private definition you see that it uses 10 digits, which is still a huge amount, but already a lot less (if we made 300k private definitions, we'd get some hash collisions).<br>
Secondly, it depends on how you generate these hashes. For private definitions, no random number generator is used, so that the name will be the same if you compile the (same) library twice. So it computes it based on some data about the library. In Lean 2 we got a hash collision this way (<a href="https://github.com/leanprover/lean/issues/648">leanprover/lean#648</a>), since for two private declarations this data was exactly the same.</p>



<a name="258534613"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/error%3A%20unknown%20declaration%20_private/near/258534613" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Floris van Doorn <a href="https://leanprover-community.github.io/archive/stream/113488-general/topic/error.3A.20unknown.20declaration.20_private.html#258534613">(Oct 21 2021 at 12:20)</a>:</h4>
<p>I just got another curious error message in the <code>export as low-level text file</code> step:</p>
<div class="codehilite" data-code-language="Text only"><pre><span></span><code>/home/ghrunner/actions-runner/_work/_temp/0b458b3b-45ef-4c14-a948-d0340aaa6393.sh: line 1: 1393818 Killed                  lean --recursive --export=mathlib.txt src/
</code></pre></div>
<p><a href="https://github.com/leanprover-community/mathlib/runs/3963242676">https://github.com/leanprover-community/mathlib/runs/3963242676</a></p>



{% endraw %}

<hr><p>Last updated: Jan 25 2023 at 00:06 UTC</p>