---
layout: archive
title: Zulip Chat Archive
permalink: /stream/113489-new-members/topic/lean3.20throwing.20exception.20on.20Ubuntu.2020.2E04.html
---

<h2>Stream: <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/index.html">new members</a></h2>
<h3>Topic: <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/lean3.20throwing.20exception.20on.20Ubuntu.2020.2E04.html">lean3 throwing exception on Ubuntu 20.04</a></h3>

<hr>

<base href="https://leanprover.zulipchat.com/">

<head><link href="/style.css" rel="stylesheet"></head>

{% raw %}

<a name="243296415"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/lean3%20throwing%20exception%20on%20Ubuntu%2020.04/near/243296415" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Morten Brodersen <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/lean3.20throwing.20exception.20on.20Ubuntu.2020.2E04.html#243296415">(Jun 20 2021 at 10:11)</a>:</h4>
<p>I have installed elan and lean3 (stable 3.30.0) on Ubuntu 20.04. Running the following command:</p>
<hr>
<p>lean -run src/misc/hello-world.lean</p>
<hr>
<p>on this file (hello-world.lean):</p>
<hr>
<p>import <a href="http://system.io">system.io</a></p>
<p>open io</p>
<p>def main : io unit := do<br>
  return ()</p>
<hr>
<p>results in this error message:</p>
<hr>
<p>terminate called after throwing an instance of 'std::logic_error'<br>
  what():  basic_string::_S_construct null not valid</p>
<hr>
<p>which seems to be a C++ exception.</p>
<p>Any help would be very much appreciated :-)</p>



<a name="243296588"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/lean3%20throwing%20exception%20on%20Ubuntu%2020.04/near/243296588" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Eric Wieser <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/lean3.20throwing.20exception.20on.20Ubuntu.2020.2E04.html#243296588">(Jun 20 2021 at 10:16)</a>:</h4>
<p>(a tip for using zulip: <a href="https://github.com/leanprover-community/mathlib/wiki/Code-in-backticks">#backticks</a>)</p>



<a name="243297328"></a>
<h4><a href="https://leanprover.zulipchat.com/#narrow/stream/113489-new%20members/topic/lean3%20throwing%20exception%20on%20Ubuntu%2020.04/near/243297328" class="zl"><img src="https://leanprover-community.github.io/archive/assets/img/zulip2.png" alt="view this post on Zulip"></a> Morten Brodersen <a href="https://leanprover-community.github.io/archive/stream/113489-new-members/topic/lean3.20throwing.20exception.20on.20Ubuntu.2020.2E04.html#243297328">(Jun 20 2021 at 10:40)</a>:</h4>
<p>My bad. It was a configuration problem. It works now.</p>



{% endraw %}

<hr><p>Last updated: Jan 25 2023 at 00:06 UTC</p>