[
    {
        "content": "<p>Any idea what happened here?</p>\n<p><a href=\"https://github.com/leanprover-community/mathlib/runs/2350890535?check_suite_focus=true\">https://github.com/leanprover-community/mathlib/runs/2350890535?check_suite_focus=true</a></p>",
        "id": 234658881,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1618486616
    },
    {
        "content": "<p>This happened to me too, and then a few hours later I got a diagnosis. <span class=\"user-mention\" data-user-id=\"110043\">@Gabriel Ebner</span> do you think this is something to do with the recent \"build twice\" idea?</p>",
        "id": 234671067,
        "sender_full_name": "Kevin Buzzard",
        "timestamp": 1618491998
    },
    {
        "content": "<p>I think this is a github issue.  If it was on our end, there would be a build log.</p>",
        "id": 234671174,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1618492051
    },
    {
        "content": "<p>Here's my version: <a href=\"https://github.com/leanprover-community/mathlib/runs/2346014022\">https://github.com/leanprover-community/mathlib/runs/2346014022</a> . I take back my assertion that it started working later -- this must have been another commit.</p>",
        "id": 234671484,
        "sender_full_name": "Kevin Buzzard",
        "timestamp": 1618492163
    }
]