[
    {
        "content": "<p>Hmm, a strange error:</p>\n<div class=\"codehilite\"><pre><span></span>&gt; lean --make .\n&gt; lean --make test\n&gt; lean --recursive --export=mathlib.txt\n&lt;unknown&gt;:1:1: error: invalid object declaration, environment already has an object named &#39;category_theory.limits.category_theory.limits.has_limits._proof_1&#39;\n</pre></div>",
        "id": 135790347,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1539545649
    },
    {
        "content": "<p>How come it doesn't complain with <code>lean --make</code>?</p>",
        "id": 135790352,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1539545671
    },
    {
        "content": "<p>Is this that two files, which are never imported in the same place, have the same named definition? And this isn't detected until the last run of lean?</p>",
        "id": 135790362,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1539545715
    },
    {
        "content": "<p>(Doesn't matter too much, there was an instance that should have been a def anyway, that should solve this.)</p>",
        "id": 135790418,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1539545817
    },
    {
        "content": "<blockquote>\n<p>Is this that two files, which are never imported in the same place, have the same named definition? And this isn't detected until the last run of lean?</p>\n</blockquote>\n<p>That's right</p>",
        "id": 135790980,
        "sender_full_name": "Simon Hudon",
        "timestamp": 1539546785
    }
]