[
    {
        "content": "<p>Did we switch to the Hoskinson runners? <span aria-label=\"open mouth\" class=\"emoji emoji-1f62e\" role=\"img\" title=\"open mouth\">:open_mouth:</span><br>\n<a href=\"https://github.com/leanprover-community/mathlib/actions/runs/2881041418\">https://github.com/leanprover-community/mathlib/actions/runs/2881041418</a> mentions <code>hoskinson4</code>.</p>",
        "id": 294038873,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1660814323
    },
    {
        "content": "<p>did you notice it reported an error at Build mathlib: src/analysis/convex/slope.lean#L103</p>",
        "id": 294039519,
        "sender_full_name": "Junyan Xu",
        "timestamp": 1660814633
    },
    {
        "content": "<p>Actually, I hadn't. Thanks! Why isn't it showing up as usual?</p>",
        "id": 294039885,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1660814772
    },
    {
        "content": "<p>It's at the bottom of the page <a href=\"https://github.com/leanprover-community/mathlib/actions/runs/2881041418/attempts/1\">https://github.com/leanprover-community/mathlib/actions/runs/2881041418/attempts/1</a> below two other error messages, one of which is the usual \"lost connection\", and the other an obscure long message I never seen ... I saw you triggered a rerun so I guessed you didn't notice.</p>",
        "id": 294080534,
        "sender_full_name": "Junyan Xu",
        "timestamp": 1660830518
    }
]