[
    {
        "content": "<p>I just made <a href=\"https://github.com/leanprover-community/mathlib/pull/12568\">#12568</a>, which segfaults for me every time in gitpod. However, github reports that it built everything downstream of <a href=\"https://tqft.net/mathlib/algebra/order/monoid\">file#algebra/order/monoid</a> in just 16s!</p>\n<p>I assume what actually happened is that the build segfaulted in CI too, but CI considered that a pass?</p>",
        "id": 274848375,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1646925272
    },
    {
        "content": "<p>Ah, seems only the build step swallowed the error, lint and tests segfault too <a href=\"https://github.com/leanprover-community/mathlib/runs/5498018633?check_suite_focus=true\">and report it</a></p>",
        "id": 274849455,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1646925742
    },
    {
        "content": "<p>Here's a <a href=\"https://leanprover-community.github.io/mwe.html\">#mwe</a> for the segfault:</p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code><span class=\"kn\">import</span> <span class=\"n\">algebra.group.with_one</span>\n\n<span class=\"c1\">-- segfault without this line</span>\n<span class=\"c1\">-- attribute [semireducible] with_zero</span>\n\n<span class=\"kd\">def</span> <span class=\"n\">segfault_please</span> <span class=\"o\">:</span> <span class=\"n\">with_zero</span> <span class=\"n\">ℕ</span> <span class=\"bp\">→</span> <span class=\"n\">ℕ</span>\n<span class=\"bp\">|</span> <span class=\"mi\">0</span> <span class=\"o\">:=</span> <span class=\"mi\">0</span>\n<span class=\"bp\">|</span> <span class=\"o\">(</span><span class=\"n\">n</span> <span class=\"o\">:</span> <span class=\"n\">ℕ</span><span class=\"o\">)</span> <span class=\"o\">:=</span> <span class=\"n\">n</span>\n</code></pre></div>",
        "id": 274860314,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1646930029
    },
    {
        "content": "<p><span aria-label=\"scream\" class=\"emoji emoji-1f631\" role=\"img\" title=\"scream\">:scream:</span></p>",
        "id": 274870287,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1646934293
    },
    {
        "content": "<blockquote>\n<p>Ah, seems only the build step swallowed the error, lint and tests segfault too and report it</p>\n</blockquote>\n<p>Is this because we don't set pipefail in ci?</p>",
        "id": 274870477,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1646934365
    },
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/lean/pull/695\">lean#695</a></p>",
        "id": 274870866,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1646934565
    }
]