[
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/mathlib/pull/15170/commits/05a33f9c9367397028c130860637a37e8ea3cc7c\">This commit</a> in <a href=\"https://github.com/leanprover-community/mathlib/pull/15170\">#15170</a> fails with the error \"unexpected occurrence of recursive function\", which <a href=\"https://github.com/leanprover-community/mathlib/pull/15170#pullrequestreview-1032173686\">seems to be originating from the <code>tauto</code> tactic</a>.  Is this a bug in <code>tauto</code>?</p>",
        "id": 288867753,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1657228939
    }
]