[
    {
        "content": "<p>On <a href=\"https://github.com/leanprover-community/mathlib/issues/10188\">#10188</a>, the build failed twice (because of offline runners) but restarting the build finally succeeded. However, fetching the oleans with <code>leanproject up</code> doesn't get working oleans. As you can see in <a href=\"https://github.com/leanprover-community/mathlib/runs/4202480686?check_suite_focus=true\">https://github.com/leanprover-community/mathlib/runs/4202480686?check_suite_focus=true</a>, the <code>push release to azure</code> step skipped the file. Might that be related? Is that fixable?</p>",
        "id": 261562580,
        "sender_full_name": "Sebastien Gouezel",
        "timestamp": 1637012090
    },
    {
        "content": "<p><code>curl -I https://oleanstorage.azureedge.net/mathlib/9520db71ee2c817adf059426c81a58d369bacd51.tar.xz</code> seems to work.</p>",
        "id": 261563548,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637012555
    },
    {
        "content": "<p>Also <code>leanproject</code> works for me.</p>",
        "id": 261563801,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637012675
    },
    {
        "content": "<p><code>leanproject</code> works for me, but oleans are not up to date. I.e.,</p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code> <span class=\"n\">lean</span> <span class=\"c1\">--make .\\src\\topology\\metric_space\\hausdorff_dimension.lean</span>\n</code></pre></div>\n<p>starts recompiling <code>nat/pow.lean</code>.</p>",
        "id": 261563977,
        "sender_full_name": "Sebastien Gouezel",
        "timestamp": 1637012762
    },
    {
        "content": "<p>It looks like the first run already uploaded the wrong oleans, but unfortunately the log file is cut off: <a href=\"https://github.com/leanprover-community/mathlib/runs/4193969798?check_suite_focus=true\">https://github.com/leanprover-community/mathlib/runs/4193969798?check_suite_focus=true</a></p>",
        "id": 261564664,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637013115
    },
    {
        "content": "<blockquote>\n<p>Is that fixable?</p>\n</blockquote>\n<p>We could remove the file from the cache, and then rerun the CI job.</p>",
        "id": 261565032,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637013293
    },
    {
        "content": "<p>But it's probably easier to just push a new commit to the branch.</p>",
        "id": 261565049,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637013305
    },
    {
        "content": "<p>I meant: is that fixable by CI that a second run does not skip uploading to azure if the first run was not successful? On this particular commit, sure, pushing a new commit is the simplest thing to do.</p>",
        "id": 261566049,
        "sender_full_name": "Sebastien Gouezel",
        "timestamp": 1637013732
    },
    {
        "content": "<p>We want to upload oleans even if the build fails (= is not successful).  I'm not sure how we can detect the difference to this situation here.</p>",
        "id": 261566950,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637014168
    },
    {
        "content": "<p>We also don't want to update existing caches (because that's even weirder to debug).</p>",
        "id": 261566981,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637014187
    },
    {
        "content": "<p>We've had such a problem a long time ago as well, and we \"fixed\" it by running lean twice.</p>",
        "id": 261567077,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637014215
    },
    {
        "content": "<p>Maybe we just need to run lean three times in a row now?</p>",
        "id": 261567099,
        "sender_full_name": "Gabriel Ebner",
        "timestamp": 1637014224
    }
]