[
    {
        "content": "<p>After installing Lean4 following <a href=\"https://leanprover.github.io/lean4/doc/setup.html\">the basic setup</a> I am no longer able to run <code>leanproject new [PATH]</code> to create a new lean project. It returns uncaught exception. It only works to create a Lean3 project if I run it from within the directory of an already existing Lean3 project. Is this what it should happen? What do I have to do in order to create a Lean3 projects now?</p>",
        "id": 228617726,
        "sender_full_name": "Horatiu Cheval",
        "timestamp": 1614787533
    },
    {
        "content": "<p>Probably setting elan's default Lean to Lean 4 is breaking things. Try <code>elan default stable</code>.</p>",
        "id": 228619075,
        "sender_full_name": "Bryan Gin-ge Chen",
        "timestamp": 1614787982
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"329243\">@Horatiu Cheval</span> <code>leanproject</code> was designed for lean3, I would be surprised if it just works with lean4...</p>",
        "id": 228619812,
        "sender_full_name": "Johan Commelin",
        "timestamp": 1614788227
    },
    {
        "content": "<p>I see, I wasn't trying that. The problem was I was no longer able to use it for Lean3</p>",
        "id": 228620331,
        "sender_full_name": "Horatiu Cheval",
        "timestamp": 1614788398
    },
    {
        "content": "<p>But <code>elan default stable</code> fixed it.</p>",
        "id": 228620460,
        "sender_full_name": "Horatiu Cheval",
        "timestamp": 1614788427
    }
]