[
    {
        "content": "<p>I tried replacing some lemma/def arguments with variables in PR <a href=\"https://github.com/leanprover-community/mathlib/pull/13307\">#13307</a>, and it seems to have broken something, since the Lint mathlib check is failing. I don't understand the error message, though. It says: </p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code><span class=\"n\">Run</span> <span class=\"n\">set</span> <span class=\"bp\">-</span><span class=\"n\">o</span> <span class=\"n\">pipefail</span>\n<span class=\"n\">info</span><span class=\"o\">:</span> <span class=\"n\">downloading</span> <span class=\"n\">installer</span>\n<span class=\"n\">curl</span><span class=\"o\">:</span> <span class=\"o\">(</span><span class=\"mi\">22</span><span class=\"o\">)</span> <span class=\"n\">The</span> <span class=\"n\">requested</span> <span class=\"n\">URL</span> <span class=\"n\">returned</span> <span class=\"n\">error</span><span class=\"o\">:</span> <span class=\"mi\">404</span>\n<span class=\"n\">elan</span><span class=\"o\">:</span> <span class=\"n\">command</span> <span class=\"n\">failed</span><span class=\"o\">:</span> <span class=\"n\">curl</span> <span class=\"bp\">-</span><span class=\"n\">sSfL</span> <span class=\"n\">https</span><span class=\"o\">:</span><span class=\"bp\">//</span><span class=\"n\">github.com</span><span class=\"bp\">/</span><span class=\"n\">leanprover</span><span class=\"bp\">/</span><span class=\"n\">elan</span><span class=\"bp\">/</span><span class=\"n\">releases</span><span class=\"bp\">/</span><span class=\"n\">download</span><span class=\"bp\">//</span><span class=\"n\">elan</span><span class=\"bp\">-</span><span class=\"n\">x86_64</span><span class=\"bp\">-</span><span class=\"n\">unknown</span><span class=\"bp\">-</span><span class=\"n\">linux</span><span class=\"bp\">-</span><span class=\"n\">gnu.tar.gz</span> <span class=\"bp\">-</span><span class=\"n\">o</span> <span class=\"bp\">/</span><span class=\"n\">tmp</span><span class=\"bp\">/</span><span class=\"n\">tmp.B0Iqdr9jt0</span><span class=\"bp\">/</span><span class=\"n\">elan</span><span class=\"bp\">-</span><span class=\"n\">init.tar.gz</span>\n<span class=\"n\">Error</span><span class=\"o\">:</span> <span class=\"n\">Process</span> <span class=\"n\">completed</span> <span class=\"k\">with</span> <span class=\"n\">exit</span> <span class=\"n\">code</span> <span class=\"mi\">1</span><span class=\"bp\">.</span>\n</code></pre></div>\n<p>Does anyone know what this means, or how I can fix it?</p>",
        "id": 281818781,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652187063
    },
    {
        "content": "<p>You need to merge master to get some fixes to the CI setup</p>",
        "id": 281819537,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1652187391
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"310045\">@Eric Wieser</span>  I tried merging from master in VSCode and then syncing, but it doesn't seem to have done anything. I'm not sure whether I did it wrong or not</p>",
        "id": 281827746,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652191233
    },
    {
        "content": "<p>The error message is from github not vscode</p>",
        "id": 281827856,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1652191283
    },
    {
        "content": "<p>You'll need to push after merging and wait to see if it fixes github</p>",
        "id": 281827879,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1652191299
    },
    {
        "content": "<p>Right yeah, I made a new commit after trying to merge from master and it still failed</p>",
        "id": 281828677,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652191624
    },
    {
        "content": "<p>I don't see a merge commit on the PR page? Are you sure you pushed the merge commit to GitHub? <a href=\"https://github.com/leanprover-community/mathlib/pull/13307\">https://github.com/leanprover-community/mathlib/pull/13307</a></p>",
        "id": 281828881,
        "sender_full_name": "Bryan Gin-ge Chen",
        "timestamp": 1652191707
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"123965\">Bryan Gin-ge Chen</span> <a href=\"#narrow/stream/113489-new-members/topic/Strange.20error.20in.20.22Lint.20mathlib.22.20check/near/281828881\">said</a>:</p>\n<blockquote>\n<p>I don't see a merge commit on the PR page? Are you sure you pushed the merge commit to GitHub? <a href=\"https://github.com/leanprover-community/mathlib/pull/13307\">https://github.com/leanprover-community/mathlib/pull/13307</a></p>\n</blockquote>\n<p>I am very unsure. What I did was: clicked on the little ... in the \"Source Control\" of VSCode, went to Branch -&gt; Merge Branch, selected the branch origin/master, made some trivial change to my code so that it let me make a new commit, and then committed it</p>",
        "id": 281829688,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652192097
    },
    {
        "content": "<p>Was it this commit? <a href=\"https://github.com/leanprover-community/mathlib/pull/13307/commits/b453a429dce7169742096b202842fd2596c15ca3\">https://github.com/leanprover-community/mathlib/pull/13307/commits/b453a429dce7169742096b202842fd2596c15ca3</a></p>\n<p>If so, it doesn't look like it contains a merge with the latest <code>master</code>. You might have to fetch the latest version of master before merging. <code>git fetch &amp;&amp; git merge origin/master</code> is what I usually run from the command line.</p>",
        "id": 281830324,
        "sender_full_name": "Bryan Gin-ge Chen",
        "timestamp": 1652192372
    },
    {
        "content": "<p>It worked! Thank you both</p>",
        "id": 281833216,
        "sender_full_name": "Sebastian Monnet",
        "timestamp": 1652193489
    }
]